### ISSUE TITLE
Getting content securiy warning in rails 5.2

### ISSUE THREAD

**Issue by tachyons** [TrestleAdmin/trestle-tinymce#1]
I am trying to use this plugin in a rails 5.2 project with default content securty options. I am getting this warning and TinyMCe is not getting loaded 

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;!function(){var t,e,n,o=0,u=function(t,.... new:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
>       Trestle.i18n['trestle.confirmatio.... new:76
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
> //<![CDATA[
> Trestle.TinyMCE.default = {....

**Comment by spohlenz** [comment]
Can you post the contents of your `config/initializers/content_security_policy.rb`? I was under the impression that it was all commented out by default and hence not enabled (although I haven't explored it too far yet to be honest).

**Comment by tachyons** [comment]
My content policy script was
```ruby
Rails.application.config.content_security_policy do |policy|
  if Rails.env.development?
    policy.script_src :self, :https, :unsafe_eval
  else
    policy.script_src :self, :https
  end
end
```
Fixed using the workaround
```ruby
Rails.application.config.content_security_policy do |policy|
  if Rails.env.development?
    policy.script_src :self, :https, :unsafe_eval, :unsafe_inline
  else
    policy.script_src :self, :https, :unsafe_inline
  end
end
```

**Comment by tachyons** [comment]
Related https://github.com/tinymce/tinymce/issues/1901
