### ISSUE TITLE
How do i make with setup in Trestle use tinymce ?

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle-tinymce#4]
tinymce.init({
            selector: ".tinymce",  // change this to target the appropriate HTML control on your page
            setup: function (editor) { // on the setup of the TinyMCE plugin, add a button with the alias 'addImage'
                editor.addButton('addImage', {
                    text: 'Add Image', // the text to display alongside the button
                    icon: 'image', // the icon to display alongside the button
                    onclick: function () {
                        activeTextArea = editor; // onclick of this button, set the active textarea to that of which the button was pressed
                        $('#filePicker').modal('show'); // show the file picker modal
                    }
                });
            },

@spohlenz

**Comment by spohlenz** [comment]
You can extend the default TinyMCE configuration options within `config/initializers/trestle.rb`. See the README for some examples. If you want to use a function like in your example, pass it as as string but ensure it begins with the string `function`:

```ruby
config.tinymce.default.configure do |c|
  c.setup = <<-SETUP.strip_heredoc
    function (editor) {
      editor.addButton('addImage', {
        text: 'Add Image', // the text to display alongside the button
        icon: 'image', // the icon to display alongside the button
        onclick: function () {
          activeTextArea = editor; // onclick of this button, set the active textarea to that of which the button was pressed
          $('#filePicker').modal('show'); // show the file picker modal
        }
      });
    }
  SETUP
end
```

If you wish to initialize TinyMCE manually then you might prefer to use the [tinymce-rails](https://github.com/spohlenz/tinymce-rails) gem directly.
