### ISSUE TITLE
Failed to initialize plugins

### ISSUE THREAD

**Issue by Tao-Galasse** [TrestleAdmin/trestle-tinymce#7]
Hi!

I just updated my app from Rails 5.2 to Rails 6, and since then I have these warnings messages while accessing a view with the `editor` method in the form :
`Failed to initialize plugin: lists` 
`Failed to initialize plugin: link`
(with all the 8 plugins from the default config).

Any idea about what can cause this? 🙏

**Comment by spohlenz** [comment]
I haven't been able to reproduce this but one thing I would try is to clear out your Sprockets cache:

```sh
bundle exec rails tmp:cache:clear
```

If that doesn't help can you please post your versions of the following (or your Gemfile/Gemfile.lock):

1. trestle-tinymce (gem or GitHub master?)
2. sprockets
3. sprockets-rails

**Comment by Tao-Galasse** [comment]
Clear the cache didn't solve the issue.

I'm running `trestle-tinymce (0.3.0)` in my Gemfile.lock (from rubygem, `gem 'trestle-tinymce'` in the Gemfile)

Initially, I was running :
```
sprockets 3.7.2
sprockets rails 3.2.1
```

Due to this issue, I tried to update these versions to the latest. The versions were locked by sass-rails 5.1.0, so I updated it to run :
```
sass-rails 6.0.0
sprockets 4.0.2
sprockets rails 3.2.2
```

But I still got this issue.

**Comment by Tao-Galasse** [comment]
Here's my full Gemfile.lock : https://gist.github.com/Tao-Galasse/c2ffa5ceb356ead2f2cbdc32c5f78ab5

**Comment by spohlenz** [comment]
No clues there that I can spot unfortunately.

Do you see any errors, either in your rails server console logs or within your browser network tab? For example, here is where I see the TinyMCE plugins being loaded within Chrome:

<img width="1706" alt="Screen Shot 2020-09-21 at 8 35 47 pm" src="https://user-images.githubusercontent.com/7600/93759906-3bd7cf80-fc4a-11ea-8097-2f2cc3a7eada.png">

**Comment by Tao-Galasse** [comment]
<img width="1680" alt="Capture d’écran 2020-09-21 à 17 13 20" src="https://user-images.githubusercontent.com/32199278/93784900-cc53e700-fc2d-11ea-96e0-9470e4bba4c3.png">
Hum, it's really strange; it seems like they are loaded but they don't appear in the MCE 🤔

**Comment by spohlenz** [comment]
It looks like there are some errors in the console -- are any of them possibly relevant to the issue?

One other thing to check is if you have a content security policy enabled and if it works without it.

**Comment by Tao-Galasse** [comment]
Oh, yes, I didn't even see it 🤦‍♂️ Sorry about it. Here are the errors :
<img width="1666" alt="Capture d’écran 2020-09-22 à 18 23 13" src="https://user-images.githubusercontent.com/32199278/93910022-d0046e00-fd00-11ea-9f3c-8bba9487225c.png">
Could it could be an issue with the asset pipeline and / or a confusion between sprockets & webpacker due to the upgrade to rails 6 ? To be honest, I've never really understood how it works 😅 Usually, I'm only using rails in api-only.

**Comment by spohlenz** [comment]
This actually looks like the versions of the plugins that are being loaded are still coming from TinyMCE 4.x, whereas your main TinyMCE script is loading 5.x.

Do you have any stale precompiled assets within your `public/assets` folder? If so, delete them (or rerun `rails assets:precompile`) and the latest versions should hopefully start loading.

**Comment by Tao-Galasse** [comment]
That was the issue! Everything's fine now. Thank you very much for taking time for me @spohlenz 🙂 🙏
